# Exploring lore format

In [1]:
import pandas as pd
import numpy as np
import pickle
from pathlib import Path
import sys
np.random.seed(10)
import bz2
import pickle

def save_pickle_bz2(path: str, obj):
    """Saves a pickle file compressed in BZ2 format.

    Args:
        path (str): Path where to save object.
        obj (Any): Object to save.
    """
    with bz2.open(path, "wb") as f:
        pickle.dump(obj, f)
def load_pickle_bz2(path):
    """
    Loads data saved with save_pickle_bz2

    Args:
        path (str): Path where the data are located

    Returns:
        loaded object
    """
    with bz2.BZ2File(path) as f:
        data = pickle.load(f)
    return data

In [2]:
!pip install bitarray

In [3]:
sys.path.append("../LORE_sa/")
sys.path.append("..")

In [4]:
with open("expl_adult_RF_geneticp.sav", "rb") as f:
    l = pickle.load(f)

/home/gerardozinno/.pyenv/versions/3.9.9/envs/ml-environment/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.0.2 when using version 1.1.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [5]:
l

In [6]:
explanation = l[0]
explanation

In [7]:
dt = explanation.dt
dt

DecisionTreeClassifier()

In [8]:
save_pickle_bz2("dt.bz2", dt)

# LOADING ADULT

In [9]:
PATH = Path("../../notebooks/datasets/adult/adult_randomforest_and_datasets/")

In [10]:
loaded = np.load(PATH / "adult_randfor.data.npz")

In [11]:
for k in loaded.keys():
    print(k, end=" ")

x_train x_test y_train y_test x_test_clustered y_test_clustered 

In [12]:
X_clusters, y_clusters = loaded["x_test_clustered"],  loaded["y_test_clustered"]

In [13]:
X_clusters

array([[-7.19029045e-01,  2.18918433e-01, -2.98863912e-01,
         1.64327842e-01, -4.40433929e-01,  4.83987231e-02,
         1.16514691e-01,  6.63344752e-02,  2.63854585e-01,
         3.13954630e-01, -1.47502095e-01, -2.18673351e-01,
        -4.95443969e-01,  2.54411176e-01],
       [-7.19029045e-01,  2.18918433e-01, -2.63049867e-01,
         1.64327842e-01, -4.40433929e-01,  4.83987231e-02,
         4.11343098e-02,  1.43433438e-02,  2.63854585e-01,
         1.13782871e-01, -1.47502095e-01, -2.18673351e-01,
        -4.95443969e-01,  2.54411176e-01],
       [-7.95183500e-01,  2.18918433e-01, -4.99825759e-01,
         1.64327842e-01, -4.40433929e-01,  4.55011025e-01,
         4.11343098e-02,  4.55727703e-01,  2.63854585e-01,
         3.13954630e-01, -1.47502095e-01, -2.18673351e-01,
        -4.95443969e-01,  2.54411176e-01],
       [-7.95183500e-01,  2.18918433e-01, -1.29267749e-01,
         1.64327842e-01, -4.40433929e-01,  4.83987231e-02,
         4.11343098e-02,  1.43433438e-02,  2.

In [14]:
dt.predict(X_clusters)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [15]:
y_clusters

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])

In [16]:
pwd

'/home/gerardozinno/Desktop/Tesi/Code/mlem/lore/adult'

In [17]:
cols_to_use = ['Age', 'Workclass', 'Fnlwgt', 'Education', 'Education-num', 'Marital-status', 'Occupation',
                       'Relationship', 'Race', 'Sex', 'Capital-gain', 'Capital-loss', 'Hours-per-week',
                       'Native-country']
validation_noisy = pd.read_csv("../../notebooks/datasets/adult/adult_randomforest_and_datasets/adult_validationset-noisy.csv", usecols=cols_to_use)

Problem, lore's dt sends everithing into 0 even though the 24 % of the validation set is made of 1s

In [18]:
(dt.predict(validation_noisy.to_numpy()) == 0).all()

True

In [23]:
validation_noisy = pd.read_csv("../../notebooks/datasets/adult/adult_randomforest_and_datasets/adult_testset.csv", usecols=cols_to_use)

In [24]:
(dt.predict(validation_noisy.to_numpy()) == 0).all()

True