In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification
import scipy.spatial.distance as distance
from sklearn.mixture import GaussianMixture

In [2]:
data = make_classification(n_classes=2, n_features=5, n_samples=500)
data_lime = make_classification(n_classes=2, n_features=5, n_samples=500)

In [3]:
df = pd.DataFrame(data[0])
df['Target'] = data[1]
df_lime = pd.DataFrame(data_lime[0])
df_lime['Target'] = data_lime[1]

In [4]:
class DummyBB:
    def __init__(self):
        pass
    def predict(self, x):
        return np.random.randint(2, size=len(x))
black_box = DummyBB()
black_box.predict(np.random.randn(5,3))

array([1, 1, 1, 1, 0])

In [5]:
def sample_dataset_from_gaussian_mixture(dataset, categorical_mask):
    gm = GaussianMixture(n_components=3, random_state=123).fit(dataset)
    stat_dataset = gm.sample(n_samples=5000)
    return stat_dataset

In [7]:
sample_dataset_from_gaussian_mixture(df_lime, categorical_mask=[False])

/home/gerardozinno/.pyenv/versions/ml-environment/lib/python3.9/site-packages/sklearn/utils/validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


(array([[ 7.05564683e-01,  1.84592410e+00,  2.77170475e+00,
         -1.45990904e+00, -2.02336352e-01,  9.99571087e-01],
        [ 1.21169944e+00,  1.00452079e+00, -4.02242473e-02,
          1.29763109e-01, -1.09762045e+00,  9.99361098e-01],
        [-2.87582361e+00, -2.43178788e+00, -8.71022635e-03,
         -2.20957066e+00,  2.58920172e+00,  1.00038619e+00],
        ...,
        [-1.22237988e+00, -1.53520138e+00, -1.11979415e+00,
         -8.60076139e-01,  9.25425042e-01,  5.11945963e-04],
        [-1.63450590e+00, -2.08732825e+00, -1.56711292e+00,
          1.14634850e+00,  1.22833709e+00,  4.30501175e-04],
        [-6.74525827e-01, -7.77160843e-01, -4.66157297e-01,
         -1.70970384e+00,  5.34988841e-01,  1.82790084e-03]]),
 array([0, 0, 0, ..., 2, 2, 2]))

In [8]:
gm = GaussianMixture()

In [9]:
def get_labels_distr_bin(y):
    unique, counts = np.unique(y, return_counts=True)
    print(unique)
    return np.array([x/len(y) for x in counts])

In [13]:
a, b = get_labels_distr_bin([1,0,1,0,1,1])

[0 1]


In [14]:
a

0.3333333333333333

In [15]:
def stat_sample_dataset(x_train, n_samples=8000):
    gm = GaussianMixture(n_components=3, random_state=123).fit(x_train)
    stat_dataset = gm.sample(n_samples=n_samples)
    return stat_dataset

In [17]:
a, b = stat_sample_dataset(df.drop('Target', axis=1).to_numpy())

In [18]:
a

array([[ 0.55012575, -0.54278105,  0.24938183, -1.60750234,  0.26415763],
       [ 0.7805263 , -1.30092364, -0.32961757,  0.78469063, -0.13199155],
       [ 0.83582371, -1.96589603, -1.08016128,  0.47478613, -0.68330589],
       ...,
       [-2.64121466,  2.31202654, -1.5574769 ,  1.04459641, -1.54090114],
       [-2.1548527 ,  1.72822223, -1.47169333,  0.34450012, -1.40557203],
       [-0.59325653,  0.28181663, -0.65503118,  1.48407546, -0.57217342]])

In [22]:
np.unique(b)

array([0, 1, 2])